# Generated by Django 5.0 on 2023-12-27 13:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="genre",
            field=models.CharField(
                choices=[
                    ("Triller", "Triller"),
                    ("Action", "Action"),
                    ("Horal", "Horal"),
                    ("Drama", "Drama"),
                ],
                max_length=50,
                verbose_name="Genres",
            ),
        ),
    ]
