# Generated by Django 5.0 on 2023-12-27 14:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_alter_movie_genre"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="img",
            field=models.ImageField(
                null=True, upload_to="media", verbose_name="Movie Image"
            ),
        ),
    ]
